[package]
name = "sfcore-ai-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
sfcore-ai-engine = { path = "../engine" }
tikv-jemallocator = "0.5"
